name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [linux-8.8.4]
        include:
        - name: linux-8.8.4
          ghc-ver: 8.8.4
      # complete all jobs
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Get GHC
      run: |
        sudo apt-get install --no-install-recommends -y cabal-install-3.2 ghc-${{ matrix.ghc-ver }}
        echo "/opt/cabal/bin" >> $GITHUB_PATH
        echo "/opt/ghc/${{ matrix.ghc-ver }}/bin" >> $GITHUB_PATH
    - name: Cache
      uses: actions/cache@v1
      with:
        path: /home/runner/.cabal/store/ghc-${{ matrix.ghc-ver }}
        # Prefer previous SHA hash if it is still cached
        key: ${{ matrix.name }}-${{ github.sha }}
        # otherwise just use most recent build.
        restore-keys: ${{ matrix.name }}
    - name: Link cabal project files
      run: |
        ln -s cabal.project.dist                                  cabal.project
        ln -s cabal.project.werror                                cabal.project.local
        ln -s cabal.project.dist.ghc-${{ matrix.ghc-ver }}.freeze cabal.project.freeze
    - name: Cabal update
      run: cabal update
      # Build macaw-base dependencies and crucible separately just so later
      # steps are less verbose and major dependency failures are separate.
    - name: Cabal dependencies
      run: |
        cabal build --only-dependencies macaw-base
        cabal build crucible-llvm
    - name: Cabal x86 tests
      run: cabal test macaw-x86 macaw-x86-symbolic
    - name: Cabal ASL tests
      run: cabal test macaw-asl-tests
