name: CI
on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-ver: ["8.10.7", "9.2.7", "9.4.4"]
        cabal: ["3.8.1.0"]
      # complete all jobs
      fail-fast: false
    name: macaw-loader - GHC v${{ matrix.ghc-ver }} - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Copy cabal project files
      run: |
        cp cabal.project.dist cabal.project
    - uses: haskell/actions/setup@v1
      id: setup-haskell
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal }}
    - uses: actions/cache/restore@v3
      name: Restore cabal store cache
      with:
        path: /home/runner/.cabal/store/ghc-${{ matrix.ghc-ver }}
        # Prefer previous SHA hash if it is still cached
        key: linux-${{ matrix.ghc-ver }}-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
        # otherwise just use most recent build.
        restore-keys: linux-${{ matrix.ghc-ver }}-${{ hashFiles('cabal.project.freeze') }}
    - name: Cabal update
      run: cabal update
      # Build macaw-base dependencies and crucible separately just so later
      # steps are less verbose and major dependency failures are separate.
    - name: Dependencies
      run: |
        cabal build --only-dependencies macaw-loader macaw-loader-ppc macaw-loader-aarch32 macaw-loader-x86
    - name: macaw-loader-x86
      run: |
        cabal build pkg:macaw-loader-x86
    - name: macaw-loader-aarch32
      run: |
        cabal build pkg:macaw-loader-aarch32
    - name: macaw-loader-ppc
      run: |
        cabal build pkg:macaw-loader-ppc
    - uses: actions/cache/save@v3
      name: Save cabal store cache
      if: always()
      with:
        path: /home/runner/.cabal/store/ghc-${{ matrix.ghc-ver }}
        # Prefer previous SHA hash if it is still cached
        key: linux-${{ matrix.ghc-ver }}-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
