name: Documentation

on:
  push:
    branches:
    - master

concurrency:
  # Only run one of these at a time because they update the global GitHub Pages.
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    name: Documentation
    # This matrix is defined not in order to build multiple copies of the
    # documentation in different configurations, but rather just to DRY the OS
    # and GHC version. `runs-on` can't access variables from a top-level `env`
    # block, only from `matrix`.
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
        # Latest GHC that we build with in the CI workflow
        ghc: ["9.8.2"]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: actions/cache@v4
      name: Restore Cabal cache
      env:
        key: haddock-${{ matrix.os }}-ghc${{ matrix.ghc }}
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
          dist-newstyle
        key: |
          ${{ env.key }}-${{ github.ref }}
        restore-keys: |
          ${{ env.key }}-
    - name: Build haddocks
      run: >
        cabal
        haddock
        --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs'
        --haddock-hyperlink-source
        --haddock-output-dir=doc
        --haddock-quickjump
        pkg:macaw-base
      shell: bash
    - name: Upload artifact with haddocks to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/master' &&
          github.event.pull_request.head.repo.fork == false &&
          github.repository_owner == 'GaloisInc'
      with:
        path: doc/macaw-base
    - name: Deploy haddocks to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/master' &&
          github.event.pull_request.head.repo.fork == false &&
          github.repository_owner == 'GaloisInc'
